{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elastic-operator.fullname" . }}-webhook-server-cert
  labels:
{{ include "elastic-operator.labels" . | indent 4 }}
{{- end }}