apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  # This has to be a fixed name for the elastic-operator to work
  # See: https://github.com/elastic/cloud-on-k8s/blob/f63396e905a2fbaa5f5746fc9655044bddf400f5/cmd/manager/main.go#L60
  name: elastic-webhook.k8s.elastic.co
  labels:
{{ include "elastic-operator.labels" . | indent 4 }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "elastic-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-elasticsearch-k8s-elastic-co-v1-elasticsearch
    failurePolicy: Ignore
    name: elastic-es-validation-v1.k8s.elastic.co
    rules:
      - apiGroups:
          - elasticsearch.k8s.elastic.co
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - elasticsearches
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "elastic-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-elasticsearch-k8s-elastic-co-v1beta1-elasticsearch
    failurePolicy: Ignore
    name: elastic-es-validation-v1beta1.k8s.elastic.co
    rules:
      - apiGroups:
          - elasticsearch.k8s.elastic.co
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - elasticsearches